const app=document.querySelector("#app"),progress=document.querySelector("#progress"),growthIcon=document.querySelector("#growthIcon");
const scores={sunflower:0,tulip:0,daisy:0,hibiscus:0,lotus:0};
let step=0;
const total=12;
const flowers={
 sunflower:{emoji:"🌻",name:"Sunflower",strength:"Connection",copy:"You tend to grow through connection. You notice the people around you and often find energy, meaning and support in relationships."},
 tulip:{emoji:"🌷",name:"Tulip",strength:"Compassion",copy:"You lead with gentleness. Caring for people and making space for how they feel comes naturally to you."},
 daisy:{emoji:"🌼",name:"Daisy",strength:"Appreciation",copy:"You have an eye for small bright things. You can find meaning in ordinary moments and notice what is worth appreciating."},
 hibiscus:{emoji:"🌺",name:"Hibiscus",strength:"Expression",copy:"You grow through expression. Creativity, humour, ideas and making things can help you understand yourself and connect with others."},
 lotus:{emoji:"🪷",name:"Lotus",strength:"Reflection",copy:"You are reflective and persistent. You tend to process experiences deeply and keep finding a way forward, even when things feel messy."}
};
function setProgress(n){step=n;progress.style.width=Math.min(100,(n/total)*100)+"%";growthIcon.textContent=n<3?"●":n<6?"🌱":n<10?"🌿":"🌸"}
function render(html,n=step){setProgress(n);app.innerHTML=html;window.scrollTo({top:0,behavior:"smooth"})}
function choices(items,cb){document.querySelectorAll(".choice").forEach((b,i)=>b.onclick=()=>cb(items[i],i,b))}
function start(){Object.keys(scores).forEach(k=>scores[k]=0);render(`<div class="garden">🌱 🌷 🌼 🌻</div><div class="eyebrow">a tiny garden of self-discovery</div><h1 class="hero">What flower<br>are you?</h1><p class="lead">Discover the strengths that help you grow — while learning a little about looking after your mind along the way.</p><button class="primary" id="go">Plant the seed →</button><p class="tiny">About 5 minutes · no right personality answers · not a mental-health assessment</p>`,0);document.querySelector("#go").onclick=q1}
function personality(title,text,opts,n,next){render(`<div class="eyebrow">getting to know you</div><h2 class="title">${title}</h2><p class="lead">${text}</p><div class="choices">${opts.map(o=>`<button class="choice">${o.label}</button>`).join("")}</div>`,n);choices(opts,o=>{scores[o.flower]++;next()})}
function q1(){personality("A rare free evening appears.","Where are we most likely to find you?",[{label:"🍜 Eating or hanging out with someone I love",flower:"sunflower"},{label:"🎨 Making, writing, cooking or creating something",flower:"hibiscus"},{label:"🛋️ Somewhere quiet, finally recharging",flower:"lotus"},{label:"☀️ Enjoying something simple I’ve been looking forward to",flower:"daisy"},{label:"💌 Checking in on someone I’ve been thinking about",flower:"tulip"}],1,q2)}
function q2(){personality("A friend has had an awful week.","Your first instinct is to…",[{label:"👂 Sit with them and really listen",flower:"tulip"},{label:"🍧 Get them out of the house with me",flower:"sunflower"},{label:"😂 Send something ridiculous to make them smile",flower:"hibiscus"},{label:"🧠 Give them space, then help them think it through",flower:"lotus"},{label:"🥐 Bring them a small thing they like",flower:"daisy"}],2,q3)}
function q3(){personality("Pick a tiny good thing.","Which one sounds most like something you would notice?",[{label:"A conversation that made the day better",flower:"sunflower"},{label:"Someone doing something quietly kind",flower:"tulip"},{label:"Good food, good weather, a good song",flower:"daisy"},{label:"An idea I suddenly want to make real",flower:"hibiscus"},{label:"Realising I handled something better than before",flower:"lotus"}],3,literacyIntro)}
function literacyIntro(){render(`<div class="flower-stage">🌱</div><div class="eyebrow">the weather changes</div><h2 class="title">Growing isn't only about sunshine.</h2><p class="lead">Let’s meet Sam, a university student who hasn’t quite felt like themself lately.</p><p>For several weeks, Sam has felt unusually tired, stopped looking forward to things they normally enjoy, has trouble concentrating, and has started withdrawing from friends.</p><button class="primary" id="next">What might you notice? →</button>`,4);document.querySelector("#next").onclick=signs}
function signs(){render(`<div class="eyebrow">notice the signs</div><h2 class="title">Which response fits best?</h2><p class="lead">Sam says: “I don't know. Maybe I'm just lazy. I should probably get over it.”</p><div class="choices"><button class="choice">They just need more discipline.</button><button class="choice">Several persistent changes are worth noticing and checking in about.</button><button class="choice">Everyone feels tired, so it can't mean anything.</button></div>`,5);choices([0,1,2],(_,i)=>{const msg=i===1?"Exactly. A cluster of changes that persists and affects daily life can be a reason to check in and seek support.":"Not quite. One difficult day is common, but persistent changes across mood, interest, energy or functioning deserve attention — not blame.";feedback(msg,weeds)})}
function feedback(msg,next){document.querySelector(".choices").remove();app.insertAdjacentHTML("beforeend",`<div class="feedback">${msg}</div><button class="primary" id="continue">Continue →</button>`);document.querySelector("#continue").onclick=next}
function weeds(){render(`<div class="eyebrow">pull the weeds</div><h2 class="title">Myth or fact?</h2><p class="lead"><strong>“Depression is a sign of personal weakness.”</strong></p><div class="choices"><button class="choice">🌿 Fact</button><button class="choice">🌱 Myth</button><button class="choice">🤷 Not sure</button></div>`,6);choices([0,1,2],(_,i)=>feedback(i===1?"🌱 Weed pulled. Depression is not a character flaw or a failure of willpower.":"This one is a myth. Depression is not a character flaw or a failure of willpower.",gratitude))}
function gratitude(){render(`<div class="flower-stage">☀️</div><div class="eyebrow">find some light</div><h2 class="title">A small gratitude check.</h2><p class="lead">Without forcing yourself to feel positive, what is one small thing you could appreciate today?</p><div class="choices"><button class="choice">👥 Someone in my life</button><button class="choice">🍜 Something I enjoyed</button><button class="choice">✨ Something I managed to do</button><button class="choice">🌤️ A small peaceful moment</button><button class="choice">Honestly, today was difficult.</button></div>`,7);choices([0,1,2,3,4],(_,i)=>feedback(i===4?"That counts too. Positive psychology isn't about pretending everything is good. Difficult days can simply be difficult.":"Hold onto that for a second. Noticing something good doesn't erase difficult feelings; both can exist together.",cbt))}
function cbt(){render(`<div class="eyebrow">weather the storm</div><h2 class="title">A thought isn't always the whole story.</h2><p class="lead">You get a disappointing grade and immediately think:</p><div class="feedback"><strong>“I'm terrible at this. I'm going to fail everything.”</strong></div><p>What would you say if a friend said that about themself?</p><div class="choices"><button class="choice">“Yeah… you probably will.”</button><button class="choice">“One result doesn't decide everything. Let's work out what happened and what you can do next.”</button><button class="choice">“Just don't think about it.”</button></div>`,8);choices([0,1,2],(_,i)=>feedback(i===1?"That’s a more balanced thought: it acknowledges the disappointment without turning one result into a prediction about everything.":"Try making room for the disappointment without treating the first thought as a fact. A more balanced thought might be: “This didn't go how I wanted. I can work out what happened and decide what to do next.”",breathe))}
function breathe(){render(`<div class="eyebrow">give yourself a moment</div><h2 class="title">Breathe.</h2><p class="lead">Follow the circle for a few slow breaths. Let it grow as you breathe in, and soften as you breathe out.</p><div class="breath">breathe</div><p class="tiny">Small strategies can help in difficult moments. They aren't a replacement for professional support when it is needed.</p><button class="primary" id="bloom">I'm ready to bloom →</button>`,9);document.querySelector("#bloom").onclick=result}
function result(){let max=Math.max(...Object.values(scores));let key=Object.keys(scores).find(k=>scores[k]===max);let f=flowers[key];render(`<div class="eyebrow" style="text-align:center">you've bloomed</div><div class="result">${f.emoji}</div><h2 class="result-name">You're a ${f.name}.</h2><p class="result-sub"><span class="pill">Your strength: ${f.strength}</span></p><p class="lead" style="margin-inline:auto;text-align:center">${f.copy}</p><button class="primary" id="kit" style="margin-inline:auto">Open my growth kit →</button>`,10);document.querySelector("#kit").onclick=()=>growthKit(f)}
function growthKit(f){render(`<div class="flower-stage">${f.emoji}</div><div class="eyebrow">your growth kit</div><h2 class="title">Every flower needs the right conditions to grow.</h2><p class="lead">Strengths can support us, but nobody has to manage everything alone.</p><div class="support"><div><strong>🌱 Notice</strong><br>Persistent changes in mood, interest, energy, sleep, concentration or everyday functioning are worth taking seriously.</div><div><strong>💬 Reach out</strong><br>A first sentence can be simple: “I haven't really felt like myself lately. Can I talk to you?”</div><div><strong>🧠 Get support</strong><br>If you are concerned about yourself or someone else, consider speaking with a qualified health or mental-health professional.</div></div><button class="primary" id="learn">Finish →</button>`,11);document.querySelector("#learn").onclick=end}
function end(){render(`<div class="garden">🌷 🌼 🌻 🌺 🪷</div><h2 class="title">Keep growing.</h2><p class="lead">You just explored mental-health literacy, strengths and gratitude, balanced thinking, and a brief relaxation exercise — ideas adapted from components used in the HOPE intervention.</p><div class="feedback"><strong>Important:</strong> this experience does not diagnose depression. If you are worried about persistent symptoms or your safety, seek professional help. If there is immediate danger, contact local emergency services.</div><button class="primary" id="again">Grow another flower ↻</button><p class="tiny">Campaign prototype · content should be reviewed against your course requirements and current university support information before launch.</p>`,12);document.querySelector("#again").onclick=start}
document.querySelector("#homeBtn").onclick=()=>{if(confirm("Restart the garden?"))start()};start();